### ISSUE TITLE
Didn't transfer yuque article style correctly

### ISSUE THREAD

**Issue by Hellowor1d** [ulivz/vuepress-plugin-yuque#3]
Thanks for your excellent work , it's really a good and convenient  tool ！

when I tried for this plugin ,follow the [documention](https://vuepress-plugin-yuque.ulivz.com/getting-started.html#_3-%E6%96%B0%E5%BB%BA%E4%B8%80%E4%B8%AA-vuepress-%E9%A1%B9%E7%9B%AE)

> yarn dev

but the dev pages didn't show article style correctly
like this:

![image](https://user-images.githubusercontent.com/10154292/52620470-9aba5c00-2edf-11e9-9777-ac18e9f65444.png)

![image](https://user-images.githubusercontent.com/10154292/52620601-f08f0400-2edf-11e9-8904-39fac30486a5.png)

even of my new yuque [repo](https://www.yuque.com/hellowor1d/zbysdk-doc/qsv6qk) (manually type in markdown syntax)
![image](https://user-images.githubusercontent.com/10154292/52621096-68a9f980-2ee1-11e9-9dea-dbbc2787faf0.png)

**Comment by ulivz** [comment]
This is because that the source markdown code of this repo contains `html`, but [the `html` option](https://vuepress-plugin-yuque.ulivz.com/config.html#html) in `vuepress-plugin-yuque` was disabled by default.

You can enable this option to avoid this issue.

---

BTW, actually the yuque's old doc can be written by markdown, although for now you can only use rich text. so the doc's response body would tell us which format it is and our project will respect it:

https://github.com/ulivz/vuepress-plugin-yuque/blob/450ecf1f77d3c898141d0bed11c25a867927aef8/lib/index.js#L126-L130
